[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
preDeployCommand = "npm run db:migrate"
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
